- name: Install k3s agent
  ansible.builtin.command: /usr/local/src/k3s-install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: agent
    K3S_TOKEN: "{{ hostvars[groups['k3s_master'][0]]['k3s_master_node_token'] }}"
    K3S_URL: "{{ k3s_url }}"
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s agent is running
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: true
