name: "Terraform Pipeline"

on:
  push:
    branches:
      - main
      - master
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "terraform/**"

jobs:
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/environments/production

    steps:
      - name: Checkout the repository to the job runner
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform format
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
